### ISSUE TITLE
Fonts source missing

### ISSUE THREAD

**Issue by doasu** [copypasteonly/Desire#1]
Hey there, love your theme!

Could you add hyperlinks for the fonts used in your theme? (Terminus and Waffle)
Although I didn't have much of a problem with finding Terminus, I failed to find the proper Waffle font that your theme uses.

Therefore, is it possible for you to **link to the fonts' source** to make it easier for people to enjoy your theme?

*I understand that you don't bundle fonts with your theme, but at least give us a link so that we can replicate your awesome look :)*

This is where I downloaded Terminus from: https://files.ax86.net/terminus-ttf/

**Comment by copypasteonly** [comment]
Hello, I'm glad that you like my configuration! I've already added the link to the fonts needed for the theme to work on the README. It was a little oversight on my part lol. Cheers!
